version: '3.1'

services:
  drupal:
    image: drupal:latest
    ports:
      - "80:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: your_drupal_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  db-data:
