version: "3.8"

services:
  webizly:
    image: cr432/mywebsite:test
    container_name: vers1on
    pull_policy: always
    restart: always
    networks:
       - traefik
       - backend
    ports:
      - "80"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.mywebclass.rule=Host(`www.vers1on.online`) || Host(`vers1on.online`)
      - traefik.http.routers.mywebclass.entrypoints=https
      - traefik.http.routers.mywebclass.tls=true
      - traefik.http.routers.mywebclass.tls.certresolver=simple-resolver
      - traefik.http.services.mywebclass.loadbalancer.server.port=80

networks:
  traefik:
      name: traefik
      external: true
  backend:
      external: true
